Add medication statement input and output json
minvws/nl-mgo-fhir-mapping pull request #3
Opened 2024-05-29 14:38 UTC by BartNijland91

2024-05-29 14:48 UTC, Rool submitted a review, later dismissed

2024-05-30 07:42 UTC, GrtDev requested changes

2024-05-30 07:42 UTC, GrtDev commented on medication_statement/medication_statement_output_1.json
> +}
Ik zou een array hier verwachten, aangezien er meerdere medication statements mogelijk zijn in de bundle.
```suggestion
[
    {
        "title": "Zestril tablet 10mg",
        "instructions": "1 maal per dag 1 tablet, oraal",
        "prescribedBy": "Huisartsen, niet nader gespecificeerd",
        "startDate": "2018-06-28",
        "status": "active"
    }
]
```

2024-06-03 09:18 UTC, Rool approved these changes

2024-06-03 09:18 UTC, GrtDev approved these changes

2024-06-03 09:20 UTC, merged